language: bash

sudo: required

services:
- docker

script:
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  make travis; else make lint_the_things; fi

notifications:
    email: false
    slack:
        secure: "KNo0bd7HpDB8OIGCvVBQI56RyQva9GEoWtv7kReaWlGyxsGSjFx8K1SH3xavi4Vccw+3UyTniOZ50Tbeo5T8CAF+oeWnDU4fhvZ/mzNtFiSwn7zF3k6FKsMGWKmBRsf+ClLWy1E8SlNwATSUwtOhCDXD7xp8VEpqCxcjk+esUX/IOefZmdHRcIF2Yjk/8tbm2WoluocQoB0SDRW/6fiK/JVp2wKICxZvkPEaUehUsMU4t3uZ8DwS2+e5ht2glIK8M/gqe/xf1d9YbS4EMFWngeH3rUXtpK5Ont7T5iHeYQT2F2zGMKaORKpZ6rwgrSZR6s7Y70tvpm0s36nRDRAS6x2xIRLb/6lyXuTFQDo+AZK6kuI4hLANWBrWH3vqacBecJUh4Alc5ei4xsNLVzbPQNpAtQcIZFvOgAUGaM5RKOPIRlOsr/c+szPC4GG5KUrzTeayID64ZGUS7ufEMpj708s2QdkFJjirSRsPVPFE7v64Fh40EnIbwfNKlSTOot2NDT7dRmKCkhnyfcpt6bu41Eveymxx/L2sTwe/5r1lpL82o21MvBKiJkpzsKfxity/JNUyaS/WMbckJY2iIcHKO6qTXtW8njEYP2BVdx216ge3h/86WsuUh8A7vGMF90N91XCbSURzGwyokIimzW5iwFZ3L4rF6f5g2fTmMcJPUdA="
