name: Run The Tests

on:
  pull_request:
    branches: [ mainline ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Black format
      run: |
        docker run --rm -v $(pwd):/data cytopia/black --version
        docker run --rm -v $(pwd):/data cytopia/black --check .

    - name: Markdownlint check
      run: |
        docker run --rm -i -v $(pwd):/work tmknom/markdownlint --version
        docker run --rm -i -v $(pwd):/work tmknom/markdownlint -i theme/ .

    - name: Pylint check
      run: |
        docker run --rm -v $(pwd):/data cytopia/pylint --version
        docker run --rm -v $(pwd):/data cytopia/pylint *.py

    - name: Pydocstyle check
      run: |
        docker run --rm -v $(pwd):/data cytopia/pydocstyle --version
        docker run --rm -v $(pwd):/data cytopia/pydocstyle .

  bandit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bandit check
      run: |
        echo "No official docker image yet, see https://github.com/PyCQA/bandit/issues/697"
        echo "Also: https://github.com/cytopia/docker-pylint/issues/7"
        docker run --rm -v $(pwd):/data -w /data pzelnip/codependentcodrbase:latest bandit --version
        docker run --rm -v $(pwd):/data -w /data pzelnip/codependentcodrbase:latest bandit .
        parallel echo ::: 1 2 3 4
