name: Build the Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the mainline branch
on:
  pull_request:
    branches: [ mainline ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: pzelnip/codependentcodrbase:latest
    env:
      DOCKER_USERNAME: pzelnip

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Print env vars
      run: echo "$GITHUB_REF -- $GITHUB_EVENT_NAME -- $GITHUB_SHA -- $GITHUB_HEAD_REF -- $GITHUB_BASE_REF"

    # Runs a single command using the runners shell
    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: make GH_TOKEN=foobar TRAVIS_BRANCH=$GITHUB_HEAD_REF test
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
